version: '3.7'
services:
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites:/etc/nginx/conf.d
      - ../:/app:rw
