version: '3.7'
services:
  node:
    env_file:
      - .env
    networks:
      - local
    build:
      context: node
    tty: true
    ports:
      - ${PORT}:8080
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://0.0.0.0:8080" ]
      interval: 5s
      timeout: 5s
      retries: 180
    volumes:
      - ../:/app:rw
    command: >
      sh -c "yarn up"
volumes:
  node_modules:
  next:
networks:
  backend:
    external: true
    name: lifeeka-net
  local:
    driver: overlay
